version: '3'
services:
    api:
        build:
            context: './api'
            dockerfile: Dockerfile
            target: base
        volumes:
            - ./api:/home/python/app
        container_name: mlapi-api
        expose:
            - '5200'
        ports:
            - '5200:5200'
        command: bash -c "pip install --no-cache -r requirements.txt && python app.py"
